<a href="https://colab.research.google.com/github/GaurRitika/P_Folder/blob/main/100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation.




#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
vectir = np.zeros(10)
print(vectir)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
#We can find the memory size of a NumPy array using the .nbytes attribute, or by multiplying .size with .itemsize.


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
vectir = np.zeros(10)
vectir[4] = 1
print(vectir)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
vectir = np.arange(10,50)
print(vectir)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
vectir = np.arange(10,50)
vectir = vectir[::-1]
print(vectir)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
vectir = np.arange(0,9)
vectir = vectir.reshape(3,3)
print(vectir)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
vector = np.eye(3)
print(vector)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
array = np.random.random((3,3,3))
print(array)

[[[0.73431483 0.58835163 0.68315969]
  [0.83229048 0.50398775 0.89014873]
  [0.20831107 0.40895731 0.27641218]]

 [[0.20045324 0.3581008  0.67019294]
  [0.25305328 0.37877195 0.53029024]
  [0.57029504 0.99275951 0.80912968]]

 [[0.5360408  0.55047025 0.61433205]
  [0.69153991 0.13174066 0.53086019]
  [0.79977042 0.13142319 0.09980885]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
array = np.random.random((10 , 10))
print(array)
arraymin, arraymax = array.min(), array.max()
print(arraymin, arraymax)

[[0.09108581 0.79518948 0.51822368 0.0528264  0.05228243 0.87731034
  0.40964825 0.46375318 0.76078396 0.75478211]
 [0.80715821 0.16952383 0.75838935 0.72817111 0.06342036 0.50591063
  0.75567169 0.77457874 0.8977557  0.41900316]
 [0.96679625 0.77591177 0.87213458 0.47746721 0.67904416 0.51083733
  0.84311274 0.15904543 0.59722073 0.94222234]
 [0.34557576 0.21918613 0.18309925 0.23982576 0.57131993 0.77506379
  0.04247072 0.32222605 0.78488506 0.23429848]
 [0.13299572 0.35639807 0.91033247 0.96494329 0.54736525 0.11781479
  0.94433642 0.68466745 0.03600844 0.37980771]
 [0.73636436 0.1294549  0.79273574 0.33647699 0.77423816 0.74754943
  0.578929   0.79900267 0.02737887 0.03764886]
 [0.05926578 0.36982824 0.02366568 0.95261263 0.52011484 0.17391942
  0.03541715 0.80539346 0.6131683  0.80393668]
 [0.13839125 0.36505984 0.18694805 0.37351913 0.16888518 0.78159798
  0.25122971 0.49062162 0.29622772 0.26087587]
 [0.01285966 0.1607211  0.73634767 0.75676555 0.81964816 0.26566216
  0.66465147

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
vector = np.random.random(30)
print(vector)
mean = vector.mean()
print(mean)

[0.56142165 0.39117612 0.09551019 0.26869151 0.59982458 0.86354229
 0.02442594 0.33013098 0.3497204  0.91428651 0.19222862 0.02567743
 0.74462059 0.1373107  0.13884575 0.50228069 0.79786179 0.81152088
 0.49691854 0.15484727 0.25305417 0.4338328  0.38131625 0.71894559
 0.53578933 0.9422297  0.56063318 0.7296818  0.53907498 0.383193  ]
0.46261977506012314


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [19]:
vector = np.ones((10,10))
vector[1:-1,1:-1] = 0
print(vector)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
#np.nan = “unknown”

#Unknown × 0 = still unknown

# 2 unknown equal kaise ho saktein heh
#Any comparison with NaN is False

# nan
# false
# false
# nan
# true
# false

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
vector = np.diag(1+np.arange(4),k=-1)
print(vector)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
vectir = np.zeros((8,8),dtype=int)
vectir[1::2,::]
print(vectir)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [22]:
v1 = np.random.random((5,3))
v2 = np.random.random((3,2))
print(np.dot(v1,v2))


[[0.84313447 1.30405917]
 [0.10367898 0.82608451]
 [0.68434381 1.18004447]
 [0.97675967 1.79061046]
 [1.06298372 1.48073431]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [23]:
vector = np.arange(11)
vector[(3 < vector) & (vector < 8)] *= -1
print(vector)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [24]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [26]:
np.array(0) / np.array(0)


/tmp/ipython-input-3272234849.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


np.float64(nan)

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [27]:
#intersection
vec1 = np.random.random((2 , 3))
vec2 = np.random.random((2 , 3))
print(np.intersect1d(vec1,vec2))

[]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [28]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipython-input-244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [29]:
vector = np.linspace(0,1,12,endpoint=True)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [30]:
vector = np.random.random(10)
vector.sort()
print(vector)

[0.00434286 0.10886207 0.13707634 0.17796491 0.18831769 0.3724021
 0.4446457  0.49391562 0.74113275 0.9771407 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [31]:
vector1 = np.random.random(10)
vector2 = np.random.random(10)
print(np.array_equal(vector1,vector2))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [32]:
array = np.arange(10)
array.flags.writeable = False
array[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [34]:
vector = np.random.random((10,2))
#cartesian coordinates to polar coordinates
x,y = vector[:,0], vector[:,1]
r = np.sqrt(x**2+y**2)
print(r)

[0.98914859 0.23933352 0.31473458 1.08066117 0.71107229 1.00326138
 0.44012126 0.97215336 0.76706102 1.0814648 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [35]:
vectir = np.random.random((100,2))
X,Y = np.atleast_2d(vectir[:,0], vectir[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.85212207 0.62673714 ... 1.08029461 0.77947635 0.03668915]
 [0.85212207 0.         0.39410712 ... 0.43379505 0.07317238 0.84574879]
 [0.62673714 0.39410712 0.         ... 0.80560491 0.35145996 0.63681579]
 ...
 [1.08029461 0.43379505 0.80560491 ... 0.         0.45635463 1.06054538]
 [0.77947635 0.07317238 0.35145996 ... 0.45635463 0.         0.77278525]
 [0.03668915 0.84574879 0.63681579 ... 1.06054538 0.77278525 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
vector = np.random.randint(0,10,(3,3))
print(vector)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [36]:
vector = np.random.randint(0,3,(3,10))
print((~vector.any(axis=0)).any())


False


#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [37]:
vector1 = np.arange(3).reshape(3,1)
vector2 = np.arange(3).reshape(1,3)
iterator = np.nditer([vector1,vector2,None])
for x,y,z in iterator: z[...] = x + y
print(iterator.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)